apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: kiii-project
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://postgres:5432/e-shop
    spring.datasource.username=postgres
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximum-pool-size=5
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob_non_contextual_creation=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-app-secret
  namespace: kiii-project
type: Opaque
data:
  spring.datasource.password: YjE3aTE5=
---
apiVersion: v1
kind: Deployment
metadata:
  name: kiii-project-app
  namespace: kiii-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-project-app-pod
  template:
    metadata:
      labels:
        app: kiii-project-app-pod
    spec:
      containers:
        - name: kiii-project-app
          image: borisdz/kiii-project-app
          env:
            - name: APP_URL
              value: "https://
