apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-eshop-185022
  namespace: kiii-project-borisdz-185022
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-app
                port:
                  number: 80
