apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: kiii-project-borisdz-185022
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
