apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: kiii-project-borisdz-185022
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
